repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v5.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
